spring:
  datasource:
    driver-class-name: org.postgres.Driver
    url: jdbc:postgresql://dev-db-server:5432/gymcrm_dev
    username: dev_user
    password: dev_pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"