spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://stg-db-server:5432/gymcrm_stg
    username: stg_user
    password: stg_pass

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false
    properties:
      hibernate:
        format_sql: false
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
  endpoint:
    health:
      show-dialects: always