spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gymcrm
    username: gymcrm
    password: 12345678

  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always
  prometheus:
    metrics:
      export:
        enabled: true

logging:
  level:
    root: INFO
    com.epamlab.gymcrm: DEBUG

jwt:
  secret: "k6a/62x0yKGBnpOeD8dHiXZ3Y1OD1MwbMGEulC6J9no="
  expriation: 3600000
