spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/gymcrm
    username: gymcrm
    password: 12345678

  jpa:
    # Tells Spring Boot how to handle the schema
    hibernate:
      ddl-auto: create-drop
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect
        # if you want:
        # current_session_context_class: thread

logging:
  level:
    root: INFO
    com.epamlab.gymcrm: DEBUG

storage:
  file:
    path: classpath:storage-data.txt
