server:
  port: 8081

spring:
  application:
    name: trainer-workload-service
  datasource:
    url: jdbc:h2:mem:workloaddb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  h2:
    console:
      enabled: true
  devtools:
    restart:
      enabled: false
  security:
    oauth2:
      resourceserver:
        jwt:
          secret: "k6a/62x0yKGBnpOeD8dHiXZ3Y1OD1MwbMGEulC6J9no="

  activemq:
    broker-url: tcp://localhost:61616
    user: admin
    password: admin
    packages:
      trust-all: true

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

logging:
  level:
    root: INFO
    com.gymcrm.trainerworkload: DEBUG

